# Generated by Django 4.2 on 2023-04-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchAdvice',
            fields=[
                ('da_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jobcode_da_no', models.CharField(max_length=100, null=True)),
                ('da_to', models.CharField(max_length=150, null=True)),
                ('da_cc', models.CharField(max_length=150, null=True)),
                ('da_from', models.IntegerField(null=True)),
                ('da_date', models.DateField(auto_now_add=True, null=True)),
                ('ygs_proj_defi', models.CharField(max_length=150, null=True)),
                ('job_name', models.CharField(max_length=200, null=True)),
                ('job_code', models.CharField(max_length=100, null=True)),
                ('po_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DATruckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('daID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispath_advice', to='common.dispatchadvice')),
                ('truckListID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_list', to='common.trucklist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
